name: update github secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: "the secret of the github pat"
        required: true
        type: string

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup github cli
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: authenticate github cli
        run: |
          gh auth login --with-token <<< "${{ secrets.MY_SECRET }}"\

      - name: update secret across repos
        env:
          SECRET_NAME: ${{ github.event.inputs.secret_name }}
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
        run: |
          REPOSITORIES=(
            "REPO1",
            "REPO2"
          )

          for REPO in "${REPOSITORIES[@]}"; do
            echo "updating secret in $REPO"
            gh secret set "$SECRET_NAME" -b"$SECRET_VALUE" -R "$REPO"
          done